dft_site:
    path:     /
    defaults: { _controller: dftSiteBundle:Default:index }
dft_site_contact:
    path:     /contact/
    defaults: { _controller: dftSiteBundle:Contact:index }
dft_site_menu:
    path:     /menu/
    defaults: { _controller: dftSiteBundle:Menu:index }
dft_site_menu_items:
    path:     /menu/{categoryId}
    defaults: { _controller: dftSiteBundle:Menu:index }
dft_site_cart:
    path:     /cart/
    defaults: { _controller: dftSiteBundle:Cart:index }
dft_site_payment:
    path:     /payment/
    defaults: { _controller: dftSiteBundle:Payment:index }
dft_site_login:
    path:     /login/
    defaults: { _controller: dftSiteBundle:Login:login }
dft_site_logout:
    path:     /logout/
    defaults: { _controller: dftSiteBundle:Login:logout }
dft_site_forgot_password:
    path:     /forgot-password/
    defaults: { _controller: dftSiteBundle:ForgotPassword:index }
dft_site_account:
    path:     /account/
    defaults: { _controller: dftSiteBundle:Account:index }
dft_site_orders:
    path:     /orders/
    defaults: { _controller: dftSiteBundle:Orders:index }
dft_site_delivery:
    path:     /delivery/
    methods:     [POST]
    defaults: { _controller: dftSiteBundle:Delivery:index }