dft_site:
    path:     /
    defaults: { _controller: dftSiteBundle:Default:index }
dft_site_contact:
    path:     /contact/
    defaults: { _controller: dftSiteBundle:Contact:index }
dft_site_menu:
    path:     /menu/
    defaults: { _controller: dftSiteBundle:Menu:index }
dft_site_cart:
    path:     /cart/
    defaults: { _controller: dftSiteBundle:Cart:index }