parameters:
    dft_site.api_client.class: dft\SiteBundle\Services\ApiClient
    dft_site.shopping_cart.class: dft\SiteBundle\Services\ShoppingCart
    dft_site.login.class: dft\SiteBundle\Services\Login
    dft_site.barclays_payment.class: dft\SiteBundle\Services\BarclaysPayment
    dft_site.stripe_payment.class: dft\SiteBundle\Services\StripePayment
    dft_site.form_validators.class: dft\SiteBundle\Services\FormValidators

services:
    dft_site.api_client:
        class: %dft_site.api_client.class%
        arguments: [@service_container]
    dft_site.shopping_cart:
        class: %dft_site.shopping_cart.class%
        arguments: [@service_container]
    dft_site.login:
        class: %dft_site.login.class%
        arguments: [@service_container]
    dft_site.form_validators:
        class: %dft_site.form_validators.class%
        arguments: [@service_container]
    dft_site.barclays_payment:
        class: %dft_site.barclays_payment.class%
        arguments: [@service_container]
    dft_site.stripe_payment:
        class: %dft_site.stripe_payment.class%
        arguments: [@service_container]
    kernel.listener.visitors_listener:
        class: dft\SiteBundle\EventListener\VisitorListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
