parameters:
#    dft_site.example.class: dft\SiteBundle\Example

services:
#    dft_site.example:
#        class: %dft_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
